---
-  hosts: localhost
   gather_facts: false
#   vars:
#     key_name: Ansible
   tasks:
     - name: Update the system
       command: apt-get update -y

     - name: Create EC2 instances
       ec2:
         region: ap-south-1
         key_name: Ansible
         instance_type: t2.micro
         image: ami-00b6a8a2bd28daf19
         wait: yes
         wait_timeout: 500
         instance_tags:
           name: EC2Ansible
         assign_public_ip: no
         state: present
         volumes:
           - device_name: /dev/xvda
             snapshot: snap-06c71487dfe312f0f
             volume_size: 8
       register: ec2

#     - name: Add new instance to host group
#       add_host:
#         hostname: "{{ item.public_ip }}"
#         with_items: 
#           - ec2.instances

#     - name: Terminate instances
#       ec2:
#         instance_ids: "{{ ec2.instance_ids }}"
#         state: absent
