---
-  hosts: localhost
   gather_facts: false
   become: true
   tasks:
     - name: Creating Elastic Load Balancer
       ec2_elb_lb:
         name: myelb
         state: present
         region: ap-south-1
         zones:
           - ap-south-1a
         listeners:
           - protocol: http
             load_balancer_port: 80
             instance_port: 80
       register: aws-elb

     - name: Add the instance to Load Balancer
       ec2_elb:
       args:
         instance_id: i-09757f352c54030da
         ec2_elbs: myelb
         state: present
         region: ap-south-1
       health_check:
         ping_protocol: http
         ping_port: 80
         ping_path: "/root/index.html"
         response_timeout: 5
         interval: 30
         unhealthy_threshold: 2
         healthy_threshold: 2



     
